kind: Service
apiVersion: v1
metadata:
  name: hello-cloudbuild
spec:
  selector:
    app: hello-cloudbuild
    platform: gcp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer